### ISSUE TITLE
A word of thanks

### ISSUE THREAD

**Issue by gecko984** [FilipByren/octopus-api#6]
Hey, this is not really an issue, I just didn't find any other convenient way to contact you. I just wanted to thank you for this package. I've been looking for a way to use a paid API subscription in the most efficient way. I researched maybe 3 or 4 rate limiting libraries and settled on https://github.com/vutran1710/PyrateLimiter for a few months. 

But then it became clear that it doesn't really work either and I had to research again, that's when I stumbled across Octopus API. So, for now, it's the only library that I could successfully apply to my problem - maximize API usage without getting over the limits, in the condition that sequential calls are not frequent enough.

I find this kinda surprising, because it seems to be a very common problem that a lot of people must encounter, but still I only could properly do it with Octopus API (2 starts on github) and not with any of the more popular libraries with 100+ stars.

So thank you for your work, you really saved my bacon here :)

**Comment by FilipByren** [comment]
You're welcome! I'm glad that Octopus API was able to help you solve your rate limiting problem. It can be challenging to find a library that fits your specific needs, so it's great that you were able to find one that worked for you. Had the same issue. Thank you for taking the time to let me know how Octopus API has helped you and for your kind words of appreciation. If you have any questions or need any further assistance, don't hesitate to ask.
